src/main/resources/data/nasdaqlisted.txt:
	curl ftp://ftp.nasdaqtrader.com/symboldirectory/nasdaqlisted.txt > $@

src/main/resources/data/otherlisted.txt:
	curl ftp://ftp.nasdaqtrader.com/symboldirectory/otherlisted.txt > $@

.PHONY: data
data:  src/main/resources/data/nasdaqlisted.txt src/main/resources/data/otherlisted.txt
