reddit:
  secret: c1PyjStqy4XJ1w
  thread_pool: 1

http:
  port: 8080
  host: localhost

repository:
  adapter: pg
  user: root
  password: root
  host: localhost
  port: 5432
  database: sentimental_dev
  max_conns: 25
  min_conns: 5
  conn_lifetime: 0

sentiment:
  bull:
    - dip
    - buy
    - bought
    - eod
    - hold
    - yolo
    - moon
    - calls
    - alpha
    - choo
    - call opt
    - baby
    - 💎
    - 🚀
    - 🦍
    - 📈
    - 💪
  bear:
    - down
    - sell
    - puts
    - put opt
    - 🐻
    - 🧸
    - 📉

market:
  meta:
  exceptions:
    - GME
    - AMC
    - BB
    - TSLA
    - SPY
    - PLTR
    - AAPL
    - NOK
    - NIO
    - AMD
    - NVDA
    - AMZN
    - BABA
    - MSFT
    - NFLX
    - SHOP
    - UBER
    - INTC
    - NTDOY
    # those just found in messages
    - CCIV
    - CRSR
    # weeds
    - APHA
    - WMD
    - WEED
    - TCNFF
    - GTBIF
    - CRLBF
    - CCHWF
    - AYRWF
    - MSOS
    - TLRY
    - SNDL
  ignores:
    - PE
    - TD
    - HOLD
    - FUD
    - DD
    - USD
    - ETF
    - CEO
    - IMO
    - AND
    - BIG
    - EOD
    - ALL
    - IPO
    - ITM
    - DIS
    - EV
    - PM
    - USA
    - ONE
    - WSB
    - AM
    - IT
    - OMG
    - OUT
    - SUB
    - HF
    - FOR
    - BRO
    - BOI
    - NOW
    - MORE
    - YOLO
    - LIVE
    # they mean robinhood by saying RH
    - RH
