version: "2.4"

services:
  paperhands-scraper:
    image: "ghcr.io/paperhands/backend/app.paperhands:latest"
    command: scrape
    restart: always
    environment:
      - PAPERHANDS_ENV=production
    mem_limit: 512m
    memswap_limit: 512m
    cpus: 2.0

  grafana:
    image: grafana/grafana
    depends_on:
      - timescale
      # - postgres
    ports:
      - 3000:3000
    mem_limit: 512m
    memswap_limit: 512m
    cpus: 2.0
    volumes:
      - /var/lib/grafana:/var/lib/grafana
      - /etc/grafana/provisioning:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: always
