name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: alpine
    steps:
    - uses: actions/checkout@v2
    - run: apk add make
    - run: make apk-deps alpine-install-sbt data test
