name: CI

on: push

jobs:
  package:
    runs-on: ubuntu-latest
    container:
      image: openjdk:14-jdk-alpine
    steps:
    - uses: actions/checkout@v2
    - run: apk add make
    - run: make apk-deps alpine-install-sbt data uberjar docker-package
    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.GH_USERNAME }}
        password: ${{ secrets.GH_TOKEN }}
    - run: make docker-push
