name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: openjdk:14-jdk-alpine
    steps:
    - uses: actions/checkout@v2
    - run: apk add make
    - run: make apk-deps alpine-install-sbt data uberjar docker-package
    - run: make docker-gh-login docker-push
